version: "3.9"

services:
  backend:
    build: ./new_api_deploy
    container_name: php-backend
    volumes:
      - ./new_api_deploy:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  frontend:
    build: ./project 4/project 4
    container_name: react-frontend
    ports:
      - "3000:80"

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: host.docker.internal
      PMA_PORT: 3307


volumes:
  db_data:
