services:
  backend:
    build: ./new_api_deploy
    container_name: php-backend
    ports:
      - "8080:80"
    depends_on:
      - db

  frontend:
    build: "./project 4/frontend"
    container_name: react-frontend
    ports:
      - "3000:80"

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  db_data:
